package com.muzaffar.masjidfinder.bot.enums;

import lombok.Getter;

@Getter
public enum CallbackCommand {
    LANGUAGE("LANGUAGE"),
    LOCAL_PRAYER_TIME("LPT"),  //LOCAL PRAYER TIME
    SELECTED_MJ_LOCATION("SMJL"), //SELECTED MASJID LOCATION
    SELECTED_MJ_PRAYER_TIMES("SMJPT"), //SELECTED MASJID PRAYER TIMES
    SELECTED_MJ_INFORMATION("SMJI"), //INFORMATION ABOUT SELECTED MASJID
    SET_MJ_AS_DEFAULT("SMJADL"), //SETS MASJID AS DEFAULT FOR THE USER
    BACK_FROM_MJ_INFORMATION("BFMJI"), //RETURNS USER TO ONE STEP BACK
    SEARCH_MASJID_BY_NAMES("SMBN"), //SEARCHES MASJID BY NAME'S FIRST LETTER
    CHANGE_NOTIFICATION_STATUS("CNS"), //CHANGES NOTIFICATION STATUS TO DIFFERENT

    OTHER("DIF"),
    ;

    private final String text;
    CallbackCommand(String s) {
        this.text = s;
    }
}
