spring:
  application:
    name: masjid-finder
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/masjid_bot
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  debug: false

server:
  port: 9798


telegram:
  user:
    token: 7772684659:AAEo1N2LJrxK8talgCq9V_JyEHs-vUjZM0A
    username: masjid_finder_dev_bot
  max-attempts: 5
  admin:
    token: 7108258643:AAFinJoZaaw7j2J59kUiop1RDGqrOOBB3R8
    username: prayer_time_test_bot